# Generated by Django 5.2 on 2025-04-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='favorites',
        ),
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
