# Generated by Django 5.2 on 2025-04-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_category_remove_comment_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
