# Generated by Django 5.2 on 2025-04-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_color',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_color',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
